### ISSUE TITLE
1.1 is :sad-panda:

### ISSUE THREAD

**Issue by Xcelled** [Kiplacon/RenaiTransportation#17]
In 1.1, rail signals have their collision boxes hardcoded and so can no longer be used for ramps. https://forums.factorio.com/82623

I think the way forward is to make a dummy "placer" item that then spawns the ramp (as a normal entity), like this mod does: https://github.com/Scarabytes/FactorioRealisticElectricTrains/blob/master/Realistic_Electric_Trains_0.4.5/prototypes/entities.lua. Or appeal on the forums for a reversion, but I doubt that would happen given the change was to fix a crash.

![](https://media1.tenor.com/images/bf78f1d7b25db9357105895a25b83050/tenor.gif?itemid=4891126)

**Comment by Kiplacon** [comment]
yikes
