### ISSUE TITLE
Error loading mod

### ISSUE THREAD

**Issue by stefnotch** [Kiplacon/RenaiTransportation#23]
I tried grabbing a release from GitHub and apparently it fails, because of a missing sprite?
https://github.com/Kiplacon/Renai-Transportation/blob/272d510aed3634238c7921328a530f6dbeef377f/data-final-fixes.lua#L310

![image](https://user-images.githubusercontent.com/10220080/112629942-3b0c3a00-8e35-11eb-85a2-9510bb9480b1.png)

**Comment by Kiplacon** [comment]
whops must have missed that in uploading files. Sorry about that, I'm not super familiar with github :|
Should be fixed on master branch now and I deleted and redid the 0.7.5 release

**Comment by stefnotch** [comment]
Thank you for fixing it! 😄 

Git and GitHub definitely take a while to get used to; I'm just super happy that you actually decided to use them. If you ever want to do it the fancy way, [installing git](https://git-scm.com/) or one of the [graphical clients](https://www.gitkraken.com/) is the way to go.

Then you can do stuff like
```
git clone https://github.com/Kiplacon/Renai-Transportation.git
```
to get a copy of the repository on your PC for the first time.

And afterwards, you can modify that copy of the repository and then do
```
git status
git add .
git commit -m "some message"
git push
```
and when someone else changes stuff, you just do
```
git pull
```
