### ISSUE TITLE
Extreme player bounce using Spidertron

### ISSUE THREAD

**Issue by MeowingInsanely** [Kiplacon/RenaiTransportation#24]
So my friend had a trap for me (Press f to use a launchpad kind) & so I got stuck between 2 angled bouncers (to get out of the trap I should've just rotated one of them). However bright idea was to bring my spidertron near & ride it to get out but instead the spidertron "bounced" back & forth the 2 bouncers. I tried to move the spidertron using the controller but it still didn't work, so I got off & then suddenly I was flinging far away from the bouncer until I was flung at a point FAR into the distance 🤣 (into a behemoth worm nest o_o)
Luckily we had a teleporter building mod so I put one down & went back to our base easily :)

Though I guess this is a bug or a warning to those who will try it & don't have a teleporter :P

How far I went:
![image](https://user-images.githubusercontent.com/19327202/112755072-a7439500-9011-11eb-890f-92535546cb85.png)

**Comment by Kiplacon** [comment]
lmao 😆

**Comment by Kiplacon** [comment]
On a more serious note, thanks for the description, it helps a lot to know how an issue happens. I'll try it myself and see what's up. The player launcher is actually the oldest part of the mod and isn't as "modern" as the rest of the mod so it's more likely to do stuff like this
