### ISSUE TITLE
Placing a Thrower Steam-Inserter from Bob's Logistics causes a non-recoverable error

### ISSUE THREAD

**Issue by kewne7768** [Kiplacon/RenaiTransportation#26]
With Renai Transportation and [Bob's Logistics](https://mods.factorio.com/mod/boblogistics)+deps installed, the modded thrower variants startup option enabled and the thrower variants tech researched (or sandbox+cheat mode), the following error happens when a thrower steam-inserter is placed on a running map.

```The mod Renai Transportation (0.7.5) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RenaiTransportation::on_nth_tick(3)
__RenaiTransportation__/control.lua:80: attempt to perform arithmetic on field 'electric_buffer_size' (a nil value)
stack traceback:
	__RenaiTransportation__/control.lua:80: in function <__RenaiTransportation__/control.lua:73>
```

The code already seems to have special handling for burner inserters and I'm not sure if it's worth or possible to support steam inserters (we only made one by accident and I can't imagine it's a very popular combo), but it'd be nice if it didn't error out to the title menu.

**Comment by Kiplacon** [comment]
I didn't even know inserters could run on steam lmao. After looking into it I added a simple check to exclude inserters that run on fluids from that electric_buffer_size reading so it at least shouldnt crash anymore. I only tested this with the bob's steam inserter since that's the only one I know of that runs on a fluid. I updated the files here and on the mod portal with the fix

**Comment by kewne7768** [comment]
Thanks for the quick fix (and the mod in general)! 

Small note: I think you miscredited me in the changelog, I didn't send in a fix for anything

**Comment by Kiplacon** [comment]
Whoops yeah you're right, your name should go on the first fix. There was someone else who submitted a fix too. I'll correct it in the next version
