### ISSUE TITLE
Update for 1.0

### ISSUE THREAD

**Issue by tsani** [Kiplacon/RenaiTransportation#4]
I've been using Renai Transportation in Factorio 1.0, and I'm pleased to say that most things I've tried work fine!

Here are a few things that I've noticed don't work, or produce weird behaviour.

* Hatches can't be placed on machines. Try to place a hatch on an assembling machine; it will never become green so it can be placed.
* Clicking on thrower inserters produces a chat message that just says `nil`. (EDIT: this is fixed in RT version 0.5.2.)

I'll update this issue with any new 1.0-related bugs I find as I continue playing. I'm offering to help update the mod for 1.0, but I need a bit of guidance as I haven't done much in the way of Factorio modding before.

**Comment by tsani** [comment]
Hm, it turns out I might just be using an outdated version of the mod since the `info.json` actually gives a factorio version of 1.0.

EDIT: no, I'm indeed running the latest version.

**Comment by Kiplacon** [comment]
That's very weird that the hatch doesnt work, I can place it just fine
![image](https://user-images.githubusercontent.com/12401534/92345468-672dbc80-f097-11ea-8ed2-530f999c157d.png)

Maybe another mod is messing with it. If you have any hatches already placed, can you hover one and press CTRL+SHIFT+F and open up this property on the table and paste a screenshot here to see what it says?
![image](https://user-images.githubusercontent.com/12401534/92345532-a9ef9480-f097-11ea-8a75-ef37ce3e8d57.png)
