### ISSUE TITLE
Thrower inserters do not consider in-flight items when deciding to throw

### ISSUE THREAD

**Issue by tsani** [Kiplacon/RenaiTransportation#5]
Suppose you have an open chest with an (ordinary) inserter removing items from it, and there's a thrower inserter pointed at that open chest. Suppose the open chest is full, and the ordinary inserter removes exactly one item from it. The thrower inserter sees this and begins yeeting items towards the chest. This happens *as long as* the chest is not full, even if there are items in flight that would fill the chest! The upshot is that the first thrown item lands in the chest, filling it and causing the thrower to stop, but any in-flight items will land next to the chest.

This can be worked around with the circuit network, using a condition to make the thrower active only when there is missing ~5 or 10 items from the chest, but it would be nice if this behavior were built-in. Maybe it's impossible?

**Comment by Kiplacon** [comment]
That's just how inserters work unfortunately. In some cases they'll hover over the source empty handed when the target is full (like chests and machines) other times they hover the target with the item in hand (like for belts) and my mod has the inserter throw when the arm moves past the halfway point between source and target so overfill is inevitable

It's not impossible though and I have theories on how to do it, the new update actually has an experimental version of such overflow prevention code, but it's off by default and has to be turned on in map settings. It stops overflow somewhat for belts and I have ideas on how to take flying items into account, but it'll probably be unoptimized and laggy so it's off for now

**Comment by Kiplacon** [comment]
Guess what's finally been improved on 8 months later
